In [1]:
spark.sql(
    """
    SELECT
        *
    FROM
        sdp_advance.sdp_cdc_2_silver.customers_silver_scd2
    """
)

DataFrame[address: string, city: string, customer_id: string, email: string, name: string, state: string, zip_code: string, processing_time: timestamp, source_file: string, timestamp_datetime: timestamp, __START_AT: timestamp, __END_AT: timestamp]

In [1]:
spark.sql(  
    """
    SELECT
        customer_id,
        MAX_BY(name, __START_AT)      AS name,
        MAX_BY(address, __START_AT)   AS address,
        MAX_BY(city, __START_AT) AS city,
        MAX_BY(state, __START_AT)   AS state,
  MAX_BY(zip_code, __START_AT)   AS zip_code,
  MAX_BY(__START_AT, __START_AT) AS __START_AT,
  MAX_BY(__END_AT, __START_AT)  AS __END_AT
FROM sdp_advance.sdp_cdc_2_silver.customers_silver_scd2
GROUP BY customer_id
HAVING MAX_BY(__END_AT, __START_AT) IS NOT NULL""")

DataFrame[customer_id: string, name: string, address: string, city: string, state: string, zip_code: string, __START_AT: timestamp, __END_AT: timestamp]

In [5]:
spark.sql(
    """ 
SELECT *
FROM sdp_advance.sdp_cdc_2_silver.customers_silver_scd2
WHERE customer_id IN (23225, 23617);
""")

DataFrame[address: string, city: string, customer_id: string, email: string, name: string, state: string, zip_code: string, processing_time: timestamp, source_file: string, timestamp_datetime: timestamp, __START_AT: timestamp, __END_AT: timestamp]